### ISSUE TITLE
try to make individual steps smaller

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/call-tracking-django#1]
to prevent useful content from disappearing in the embedded view mode. prefer more steps to longer ones that force crappy embedded vertical scrolling

**Comment by kwhinnery** [comment]
550px is the approximate size of the embedded viewport.

**Comment by atbaker** [comment]
Your edits in your PR were really helpful - I think I'm getting a better understanding of what to include in the prose and what to omit.

After merging your PR and reviewing the changes, everything fits in those dimensions except the first and last steps. It stinks that the first step doesn't fit, but removing the screenshot and REAME paragraph seem like a bad idea.

I'm going to leave as-is unless you have an idea about how to fix. Feel free to reopen if you do.
